# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference.proto',
  package='inference',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0finference.proto\x12\tinference\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\'\n\x13ImageClassification\x12\x10\n\x08taxonomy\x18\x01 \x01(\t\"6\n\x14\x46\x61shionMatchingMNIST\x12\x10\n\x08taxonomy\x18\x01 \x01(\t\x12\x0c\n\x04reco\x18\x02 \x03(\x05\" \n\rImageResponse\x12\x0f\n\x07res_map\x18\x01 \x01(\x0c\x32\xfd\x01\n\x0cInferenceAPI\x12N\n\x11GetClassification\x12\x17.inference.ImageRequest\x1a\x1e.inference.ImageClassification\"\x00\x12U\n\x17GetFashionMatchingMNIST\x12\x17.inference.ImageRequest\x1a\x1f.inference.FashionMatchingMNIST\"\x00\x12\x46\n\x0fGetSegmentation\x12\x17.inference.ImageRequest\x1a\x18.inference.ImageResponse\"\x00\x62\x06proto3'
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='inference.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='inference.ImageRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=59,
)


_IMAGECLASSIFICATION = _descriptor.Descriptor(
  name='ImageClassification',
  full_name='inference.ImageClassification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taxonomy', full_name='inference.ImageClassification.taxonomy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=100,
)


_FASHIONMATCHINGMNIST = _descriptor.Descriptor(
  name='FashionMatchingMNIST',
  full_name='inference.FashionMatchingMNIST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taxonomy', full_name='inference.FashionMatchingMNIST.taxonomy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reco', full_name='inference.FashionMatchingMNIST.reco', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=156,
)


_IMAGERESPONSE = _descriptor.Descriptor(
  name='ImageResponse',
  full_name='inference.ImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res_map', full_name='inference.ImageResponse.res_map', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['ImageClassification'] = _IMAGECLASSIFICATION
DESCRIPTOR.message_types_by_name['FashionMatchingMNIST'] = _FASHIONMATCHINGMNIST
DESCRIPTOR.message_types_by_name['ImageResponse'] = _IMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageClassification = _reflection.GeneratedProtocolMessageType('ImageClassification', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFICATION,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ImageClassification)
  })
_sym_db.RegisterMessage(ImageClassification)

FashionMatchingMNIST = _reflection.GeneratedProtocolMessageType('FashionMatchingMNIST', (_message.Message,), {
  'DESCRIPTOR' : _FASHIONMATCHINGMNIST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.FashionMatchingMNIST)
  })
_sym_db.RegisterMessage(FashionMatchingMNIST)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)



_INFERENCEAPI = _descriptor.ServiceDescriptor(
  name='InferenceAPI',
  full_name='inference.InferenceAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=193,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetClassification',
    full_name='inference.InferenceAPI.GetClassification',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGECLASSIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFashionMatchingMNIST',
    full_name='inference.InferenceAPI.GetFashionMatchingMNIST',
    index=1,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_FASHIONMATCHINGMNIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSegmentation',
    full_name='inference.InferenceAPI.GetSegmentation',
    index=2,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFERENCEAPI)

DESCRIPTOR.services_by_name['InferenceAPI'] = _INFERENCEAPI

# @@protoc_insertion_point(module_scope)
